type: array
description: Rule `ruleId` is not configurable | remove `ruleSetting.extraSettings`, you may only change risk level or enable/disable this rule. If you are directly copying this rule from another account and getting this message, this rule may have been previously configurable and is no longer.
items:
  type: object
  properties:
    name:
      type: string
      description: Name of the extra setting
      example: threshold
    type:
      type: string
      description: Rule specific property.
      example: regions
    countries:
      type: boolean
      description: Rule specific property.
      example: true
    regions:
      type: boolean
      description: Rule specific property.
      example: true
    multiple:
      type: boolean
      description: Rule specific property.
      example: true
    value:
      description: Customisable value for rules that take on single name/value pairs.
      example: 90
    values:
      type: array
      description: An array (sometimes of objects) rules that take on a set of of values
